apiVersion: v2
name: artifactory
description: A Helm chart for MOSIP Artifactory
type: application
version: 1.3.0-develop
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - artifactory
  - antivirus
  - anti-virus
maintainers:
  - email: info@mosip.io
    name: MOSIP
